language:
  - python
python:
  - 3.2
  - nightly
matrix:
  include:
    - python: 3.4
      env:
        - COVERALLS=1
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
after_success:
  - if [ $COVERALLS ]; then
        pip install coveralls;
        coveralls;
    fi
