language:
  - python
python:
  - 3.2
  - nightly
matrix:
  include:
    - python: 3.4
      env:
        - NOSE_WITH_COVERAGE=1
        - NOSE_COVER_TESTS=1
install:
  - pip install -r requirements.txt
script:
  - if [ $NOSE_WITH_COVERAGE ]; then
        pip install coveralls;
    fi
  - nosetests
after_success:
  - if [ $NOSE_WITH_COVERAGE ]; then
        coveralls;
    fi
