language:
  - python
python:
  - 3.2
  - 3.3
  - 3.4
  - nightly
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
after_success:
  - coveralls
